

Aşağıda hər bir tələb olunan kateqoriyadan 10 vacib funksiya və metodun siyahısı verilmişdir:

---

### **Python: String funksiyaları**
1. `.strip()` - Boşluqları və ya simvolu başdan və sondan silir.
2. `.lower()` - Bütün hərfləri kiçik edir.
3. `.upper()` - Bütün hərfləri böyük edir.
4. `.find(sub)` - Alt simvolun ilk mövqeyini tapır.
5. `.replace(old, new)` - Alt simvolu dəyişdirir.
6. `.split(sep)` - Simvolu verilən ayırıcı ilə bölür.
7. `.join(iterable)` - Iterabledakı elementləri birləşdirir.
8. `.startswith(prefix)` - Simvolun müəyyən prefiks ilə başlayıb-başlamadığını yoxlayır.
9. `.endswith(suffix)` - Simvolun müəyyən suffiks ilə bitib-bitmədiyini yoxlayır.
10. `.count(sub)` - Alt simvolun neçə dəfə təkrarlandığını sayır.

---

### **Python: List funksiyaları**
1. `.append(x)` - Siyahıya element əlavə edir.
2. `.extend(iterable)` - Siyahıya digər iterable elementlərini əlavə edir.
3. `.insert(index, x)` - Müəyyən mövqeyə element daxil edir.
4. `.remove(x)` - Siyahıdan ilk `x` dəyərini silir.
5. `.pop(index)` - Verilən indeksi və ya son elementi silib qaytarır.
6. `.clear()` - Siyahını boşaldır.
7. `.index(x)` - Elementin indeksini qaytarır.
8. `.count(x)` - Siyahıda neçə dəfə təkrarlandığını qaytarır.
9. `.sort()` - Siyahını artan sırada sıralayır.
10. `.reverse()` - Siyahını tərsinə çevirir.

---

### **Python: Dict funksiyaları**
1. `.keys()` - Bütün açarları qaytarır.
2. `.values()` - Bütün dəyərləri qaytarır.
3. `.items()` - (açar, dəyər) cütlərini qaytarır.
4. `.get(key, default)` - Açar mövcuddursa dəyər, yoxdursa default qaytarır.
5. `.pop(key)` - Açarı silir və dəyərini qaytarır.
6. `.update(other)` - Digər lüğətin cütlərini əlavə edir.
7. `.setdefault(key, default)` - Açar yoxdursa, default dəyər əlavə edir.
8. `.copy()` - Lüğətin surətini yaradır.
9. `.clear()` - Bütün açar-dəyərləri silir.
10. `len(dict)` - Lüğətin cütlərinin sayını qaytarır.

---

Yalnız funksiyaların adlarını və qısa izahlarını təqdim edirəm:

---

### **Set funksiyaları/metodları:**
1. **`add(element)`** - Yığıma yeni element əlavə edir.
2. **`remove(element)`** - Verilən elementi silir (əgər yoxdursa, səhv atır).
3. **`discard(element)`** - Verilən elementi silir (element yoxdursa, səhv atmır).
4. **`pop()`** - Təsadüfi bir elementi silir və qaytarır.
5. **`clear()`** - Bütün elementləri silir, yığını boşaldır.
6. **`union(other_set)`** - İki yığımın birləşməsini qaytarır.
7. **`intersection(other_set)`** - İki yığımın kəsişməsini qaytarır.
8. **`difference(other_set)`** - Bir yığımda olub, digərində olmayan elementləri qaytarır.
9. **`symmetric_difference(other_set)`** - İki yığım arasında olmayan fərqli elementləri qaytarır.
10. **`issubset(other_set)`** - Yığımın başqa bir yığımın alt yığını olub-olmadığını yoxlayır.

---

### **Python: Built-in funksiyalar**
1. **`print(value, ...)`** - Verilənləri ekrana çap edir.  
2. **`len(obj)`** - Verilən obyektin (məsələn, string, list) elementlərinin sayını qaytarır.  
3. **`type(obj)`** - Obyektin məlumat tipini qaytarır.  
4. **`input(prompt)`** - İstifadəçidən məlumat daxil etməyi tələb edir.  
5. **`sum(iterable, start=0)`** - İterable obyektin elementlərinin cəmini qaytarır.  
6. **`min(iterable, *[, key])`** - İterable obyektin ən kiçik elementini qaytarır.  
7. **`max(iterable, *[, key])`** - İterable obyektin ən böyük elementini qaytarır.  
8. **`sorted(iterable, *, key=None, reverse=False)`** - İterable obyektin elementlərini sıralayıb qaytarır.  
9. **`range(start, stop[, step])`** - Müəyyən interval daxilində ardıcıl rəqəmlər yaradır.  
10. **`round(number[, ndigits])`** - Verilən rəqəmi müəyyən dəqiqlikdə yuvarlaqlaşdırır.  
11. **`zip(*iterables)`** - Verilən iterable obyektləri birləşdirərək tuple-lərdən ibarət iterator yaradır.  
12. **`filter(function, iterable)`** - Şərtə uyğun gələn elementləri seçərək yeni iterator yaradır.  
13. **`map(function, iterable)`** - Verilən funksiyanı hər elementə tətbiq edərək yeni iterator yaradır.  
14. **`abs(x)`** - Verilən rəqəmin mütləq qiymətini qaytarır.  
15. **`pow(x, y[, z])`** - Rəqəmin qüvvətini hesablayır (modul parametri varsa, modula görə nəticə qaytarır).  
16. **`all(iterable)`** - İterable obyektin bütün elementləri `True` olduqda `True` qaytarır.  
17. **`any(iterable)`** - İterable obyektin hər hansı elementi `True` olduqda `True` qaytarır.  
18. **`enumerate(iterable, start=0)`** - İterable obyektin elementlərini indekslərlə birlikdə qaytarır.  
19. **`reversed(seq)`** - Verilən sıra obyektini əksinə çevirərək iterator qaytarır.  
20. **`id(obj)`** - Verilən obyektin unikal identifikatorunu qaytarır.  
21. **`hash(obj)`** - Verilən obyektin hash dəyərini qaytarır (mutable obyektlərdə işləməz).  
22. **`bin(x)`** - Verilən rəqəmin ikilik (binary) təqdimatını qaytarır.  
23. **`oct(x)`** - Verilən rəqəmin səkkizlik (octal) təqdimatını qaytarır.  
24. **`hex(x)`** - Verilən rəqəmin onaltılıq (hexadecimal) təqdimatını qaytarır.  
25. **`eval(expression)`** - Verilən string kimi ifadəni icra edir.  
26. **`exec(object)`** - Dinamik olaraq Python kodunu icra edir.  
27. **`open(file, mode)`** - Fayl açmaq üçün istifadə olunur.  
28. **`isinstance(obj, class)`** - Bir obyektin müəyyən bir sinifdən olub-olmadığını yoxlayır.  
29. **`dir([obj])`** - Verilən obyektin atributlarını və metodlarını siyahı şəklində qaytarır.  
30. **`help([obj])`** - Python obyektləri haqqında kömək və ya sənədləşmə göstərir.  

---

### **NumPy funksiyaları**
1. `np.array()` - NumPy massivini yaradır.
2. `np.zeros()` - 0-lardan ibarət massiv yaradır.
3. `np.ones()` - 1-lərdən ibarət massiv yaradır.
4. `np.arange(start, stop, step)` - Verilən intervalla massiv yaradır.
5. `np.linspace(start, stop, num)` - İki nöqtə arasında massiv yaradır.
6. `np.reshape(array, shape)` - Massivin formasını dəyişir.
7. `np.sum(array)` - Elementlərin cəmini qaytarır.
8. `np.mean(array)` - Massivin orta dəyərini qaytarır.
9. `np.std(array)` - Standart sapmanı qaytarır.
10. `np.dot(a, b)` - İki massiv arasında matris hasili qaytarır.

---

### **Matplotlib.pyplot funksiyaları**
1. `plt.plot()` - Xətti qrafik çəkir.
2. `plt.scatter()` - Nöqtə qrafiki çəkir.
3. `plt.bar()` - Bar chart yaradır.
4. `plt.hist()` - Histogram çəkir.
5. `plt.boxplot()` - Boxplot çəkir.
6. `plt.title()` - Qrafikə başlıq əlavə edir.
7. `plt.xlabel()` - X oxu üçün başlıq təyin edir.
8. `plt.ylabel()` - Y oxu üçün başlıq təyin edir.
9. `plt.legend()` - Qrafikdə əfsanə göstərir.
10. `plt.savefig()` - Qrafiki fayl kimi saxlayır.

---

### **Pandas funksiyaları**
1. `pd.read_csv()` - CSV faylını DataFrame olaraq yükləyir.
2. `pd.DataFrame()` - DataFrame yaradır.
3. `.head()` - İlk 5 sətri göstərir.
4. `.tail()` - Son 5 sətri göstərir.
5. `.info()` - DataFrame haqqında məlumat verir.
6. `.describe()` - Statistik xülasə təqdim edir.
7. `.groupby()` - Qruplaşdırma əməliyyatı aparır.
8. `.merge()` - İki DataFrame-i birləşdirir.
9. `.sort_values()` - DataFrame-i sıralayır.
10. `.drop()` - Sütun və ya sətiri silir.

---

### 🔹 **SQL Əsas Əməliyyatlar və Funksiyalar**  

| **Əməliyyat / Funksiya** | **Təsviri** | **Nümunə** |
|-------------------------|------------|------------|
| `SELECT` | Cədvəldən məlumatları seçmək üçün istifadə olunur. | `SELECT * FROM employees;` |
| `INSERT INTO` | Cədvələ yeni məlumat əlavə edir. | `INSERT INTO employees (name, age) VALUES ('Ali', 30);` |
| `UPDATE` | Mövcud məlumatları dəyişdirir. | `UPDATE employees SET age = 31 WHERE name = 'Ali';` |
| `DELETE` | Cədvəldən məlumat silir. | `DELETE FROM employees WHERE age < 25;` |
| `WHERE` | Şərt tətbiq etmək üçün istifadə olunur. | `SELECT * FROM employees WHERE age > 30;` |
| `JOIN` | İki və ya daha çox cədvəli birləşdirir. | `SELECT orders.id, customers.name FROM orders JOIN customers ON orders.customer_id = customers.id;` |
| `GROUP BY` | Məlumatları müəyyən sahəyə görə qruplaşdırır. | `SELECT department, COUNT(*) FROM employees GROUP BY department;` |
| `ORDER BY` | Nəticələri müəyyən sütuna əsasən sıralayır. | `SELECT * FROM employees ORDER BY age DESC;` |
| `LIMIT` | Nəticələrin sayını məhdudlaşdırır. | `SELECT * FROM employees LIMIT 5;` |
| `COUNT()` | Seçilmiş sətirlərin sayını qaytarır. | `SELECT COUNT(*) FROM employees;` |
| `AVG(column)` | Sütundakı ədədi dəyərlərin orta qiymətini qaytarır. | `SELECT AVG(salary) FROM employees;` |
| `SUM(column)` | Sütundakı ədədi dəyərlərin cəmini qaytarır. | `SELECT SUM(salary) FROM employees;` |
| `MIN(column)` | Verilmiş sütunda ən kiçik dəyəri qaytarır. | `SELECT MIN(salary) FROM employees;` |
| `MAX(column)` | Verilmiş sütunda ən böyük dəyəri qaytarır. | `SELECT MAX(salary) FROM employees;` |
| `HAVING` | `GROUP BY` ilə birlikdə şərt tətbiq edir. | `SELECT department, COUNT(*) FROM employees GROUP BY department HAVING COUNT(*) > 10;` |
| `DISTINCT` | Unikal dəyərləri seçir. | `SELECT DISTINCT department FROM employees;` |
| `CASE` | Şərti ifadələr yaratmaq üçün istifadə olunur. | `SELECT name, salary, CASE WHEN salary > 5000 THEN 'High' ELSE 'Low' END AS salary_level FROM employees;` |
| `LIKE` | Verilmiş şablona uyğun sətirləri seçir. | `SELECT * FROM employees WHERE name LIKE 'A%';` |
| `IN` | Bir neçə dəyəri yoxlamaq üçün istifadə olunur. | `SELECT * FROM employees WHERE department IN ('IT', 'HR');` |
| `BETWEEN` | Müəyyən aralıqda olan dəyərləri seçir. | `SELECT * FROM employees WHERE age BETWEEN 25 AND 35;` |
| `EXISTS` | Alt sorğunun nəticə qaytarıb-qaytarmadığını yoxlayır. | `SELECT * FROM employees WHERE EXISTS (SELECT 1 FROM departments WHERE department_id = employees.department_id);` |



### 🔹 **String Funksiyaları SQL**  

| **Funksiya** | **Təsviri** | **Nümunə** |
|-------------|------------|------------|
| `LENGTH(string)` | Verilmiş sətirin uzunluğunu qaytarır. | `SELECT LENGTH('Hello'); -- 5` |
| `CHAR_LENGTH(string)` | Simvolların sayını qaytarır (MySQL üçün). | `SELECT CHAR_LENGTH('Hello'); -- 5` |
| `UPPER(string)` | Sətirdəki bütün simvolları böyük hərfə çevirir. | `SELECT UPPER('hello'); -- 'HELLO'` |
| `LOWER(string)` | Sətirdəki bütün simvolları kiçik hərfə çevirir. | `SELECT LOWER('HELLO'); -- 'hello'` |
| `SUBSTRING(string, start, length)` | Sətirin müəyyən hissəsini çıxarır. | `SELECT SUBSTRING('Database', 1, 4); -- 'Data'` |
| `LEFT(string, length)` | Sətirin sol tərəfdən müəyyən sayda simvolunu qaytarır. | `SELECT LEFT('Database', 4); -- 'Data'` |
| `RIGHT(string, length)` | Sətirin sağ tərəfdən müəyyən sayda simvolunu qaytarır. | `SELECT RIGHT('Database', 4); -- 'base'` |
| `TRIM(string)` | Sətirin əvvəlində və sonunda olan boşluqları silir. | `SELECT TRIM('  Hello  '); -- 'Hello'` |
| `LTRIM(string)` | Sol tərəfdəki boşluqları silir. | `SELECT LTRIM('  Hello'); -- 'Hello'` |
| `RTRIM(string)` | Sağ tərəfdəki boşluqları silir. | `SELECT RTRIM('Hello  '); -- 'Hello'` |
| `CONCAT(string1, string2, ...)` | Verilmiş sətirləri birləşdirir. | `SELECT CONCAT('Hello', ' ', 'World'); -- 'Hello World'` |
| `CONCAT_WS(separator, string1, string2, ...)` | Verilmiş sətirləri separator ilə birləşdirir. | `SELECT CONCAT_WS('-', '2024', '07', '19'); -- '2024-07-19'` |
| `REPLACE(string, old, new)` | Sətirdə müəyyən hissəni başqa hissə ilə əvəzləyir. | `SELECT REPLACE('Hello World', 'World', 'SQL'); -- 'Hello SQL'` |
| `REVERSE(string)` | Sətiri tərsinə çevirir. | `SELECT REVERSE('SQL'); -- 'LQS'` |
| `LOCATE(substring, string)` | Alt sətirin əsas sətirdəki ilk mövqeyini qaytarır. | `SELECT LOCATE('b', 'Database'); -- 3` |
| `POSITION(substring IN string)` | Alt sətirin əsas sətirdəki ilk mövqeyini qaytarır. | `SELECT POSITION('b' IN 'Database'); -- 3` |
| `INSTR(string, substring)` | Alt sətirin ilk tapıldığı mövqeyi qaytarır (MySQL üçün). | `SELECT INSTR('Database', 'base'); -- 5` |
| `LPAD(string, length, pad_string)` | Sətiri müəyyən uzunluğa qədər sol tərəfdən tamamlayır. | `SELECT LPAD('SQL', 5, '*'); -- '**SQL'` |
| `RPAD(string, length, pad_string)` | Sətiri müəyyən uzunluğa qədər sağ tərəfdən tamamlayır. | `SELECT RPAD('SQL', 5, '*'); -- 'SQL**'` |
| `FORMAT(number, decimal_places)` | Ədədi müəyyən sayda onluq mərtəbəyə yuvarlaqlaşdırır. | `SELECT FORMAT(1234.5678, 2); -- '1,234.57'` |

### 🔹 ** SQL Say Funksiyaları (Numeric)**  

| **Funksiya** | **Təsviri** | **Nümunə** |
|-------------|------------|------------|
| `ABS(number)` | Ədədi müsbət (modul) qaytarır. | `SELECT ABS(-10); -- 10` |
| `CEIL(number)` | Verilmiş ədədi yuxarıya doğru yuvarlaqlaşdırır. | `SELECT CEIL(4.2); -- 5` |
| `FLOOR(number)` | Verilmiş ədədi aşağıya doğru yuvarlaqlaşdırır. | `SELECT FLOOR(4.9); -- 4` |
| `ROUND(number, decimals)` | Verilmiş ədədi müəyyən sayda onluq mərtəbəyə yuvarlaqlaşdırır. | `SELECT ROUND(4.567, 2); -- 4.57` |
| `TRUNCATE(number, decimals)` | Ədədi müəyyən sayda onluq mərtəbəyə qədər kəsir. | `SELECT TRUNCATE(4.567, 2); -- 4.56` |
| `MOD(a, b)` | `a` ədədinin `b`-yə bölünməsindən alınan qalığı qaytarır. | `SELECT MOD(10, 3); -- 1` |
| `POWER(a, b)` | `a` ədədini `b` qüvvətinə yüksəldir. | `SELECT POWER(2, 3); -- 8` |
| `SQRT(number)` | Ədədi kvadrat kökə çıxarır. | `SELECT SQRT(16); -- 4` |
| `EXP(number)` | `e` sabitinin (`2.718`) ədədi qüvvətini qaytarır. | `SELECT EXP(1); -- 2.718` |
| `LOG(number)` | Ədədi natural logaritmə çevirir (`ln`). | `SELECT LOG(10); -- 2.302` |
| `LOG10(number)` | 10-luq logaritm alır. | `SELECT LOG10(100); -- 2` |
| `LOG2(number)` | 2-lik logaritm alır. | `SELECT LOG2(8); -- 3` |
| `RADIANS(degree)` | Verilmiş bucağı radianlara çevirir. | `SELECT RADIANS(180); -- 3.14159` |
| `DEGREES(radian)` | Verilmiş radianı dərəcəyə çevirir. | `SELECT DEGREES(3.14159); -- 180` |
| `SIGN(number)` | Ədədin işarəsini qaytarır (-1, 0, 1). | `SELECT SIGN(-5); -- -1` |
| `RAND()` | 0 və 1 arasında təsadüfi ədəd qaytarır. | `SELECT RAND(); -- 0.7634` |
| `PI()` | Pi (`3.1415926...`) dəyərini qaytarır. | `SELECT PI(); -- 3.14159` |
| `GREATEST(value1, value2, ...)` | Verilmiş ədədlər arasında ən böyüyünü qaytarır. | `SELECT GREATEST(3, 7, 2); -- 7` |
| `LEAST(value1, value2, ...)` | Verilmiş ədədlər arasında ən kiçiyini qaytarır. | `SELECT LEAST(3, 7, 2); -- 2` |

### 🔹 ** SQL Tarix və Zaman Funksiyaları**  

| **Funksiya** | **Təsviri** | **Nümunə** |
|-------------|------------|------------|
| `CURRENT_DATE` | Cari tarixi qaytarır (YYYY-MM-DD). | `SELECT CURRENT_DATE; -- 2025-02-07` |
| `CURRENT_TIME` | Cari saatı qaytarır (HH:MI:SS). | `SELECT CURRENT_TIME; -- 14:30:15` |
| `CURRENT_TIMESTAMP` | Cari tarix və saatı qaytarır. | `SELECT CURRENT_TIMESTAMP; -- 2025-02-07 14:30:15` |
| `NOW()` | Cari tarix və saatı qaytarır. | `SELECT NOW(); -- 2025-02-07 14:30:15` |
| `DATE()` | Verilmiş datetime dəyərinin tarix hissəsini qaytarır. | `SELECT DATE(NOW()); -- 2025-02-07` |
| `TIME()` | Verilmiş datetime dəyərinin saat hissəsini qaytarır. | `SELECT TIME(NOW()); -- 14:30:15` |
| `YEAR(date)` | Tarixin ilini qaytarır. | `SELECT YEAR('2025-02-07'); -- 2025` |
| `MONTH(date)` | Tarixin ayını qaytarır (1-12). | `SELECT MONTH('2025-02-07'); -- 2` |
| `DAY(date)` | Tarixin gününü qaytarır (1-31). | `SELECT DAY('2025-02-07'); -- 7` |
| `HOUR(time)` | Vaxtın saat hissəsini qaytarır. | `SELECT HOUR('14:30:15'); -- 14` |
| `MINUTE(time)` | Vaxtın dəqiqə hissəsini qaytarır. | `SELECT MINUTE('14:30:15'); -- 30` |
| `SECOND(time)` | Vaxtın saniyə hissəsini qaytarır. | `SELECT SECOND('14:30:15'); -- 15` |
| `WEEK(date)` | Tarixin ilin neçənci həftəsinə düşdüyünü qaytarır. | `SELECT WEEK('2025-02-07'); -- 6` |
| `DAYOFWEEK(date)` | Tarixin həftənin neçənci günü olduğunu qaytarır (1 = Bazar). | `SELECT DAYOFWEEK('2025-02-07'); -- 6 (Cümə)` |
| `DAYOFYEAR(date)` | Tarixin ilin neçənci günü olduğunu qaytarır. | `SELECT DAYOFYEAR('2025-02-07'); -- 38` |
| `DATE_ADD(date, INTERVAL n unit)` | Verilmiş tarixə müəyyən interval əlavə edir. | `SELECT DATE_ADD('2025-02-07', INTERVAL 10 DAY); -- 2025-02-17` |
| `DATE_SUB(date, INTERVAL n unit)` | Verilmiş tarixdən müəyyən interval çıxır. | `SELECT DATE_SUB('2025-02-07', INTERVAL 2 MONTH); -- 2024-12-07` |
| `DATEDIFF(date1, date2)` | İki tarix arasındakı gün fərqini qaytarır. | `SELECT DATEDIFF('2025-02-07', '2025-01-01'); -- 37` |
| `TIMEDIFF(time1, time2)` | İki vaxt arasındakı fərqi qaytarır. | `SELECT TIMEDIFF('14:30:15', '12:00:00'); -- 02:30:15` |
| `TIMESTAMPDIFF(unit, date1, date2)` | İki tarix arasındakı fərqi verilən vahid üzrə qaytarır. | `SELECT TIMESTAMPDIFF(YEAR, '2000-01-01', '2025-02-07'); -- 25` |
| `STR_TO_DATE(string, format)` | Tarixi müəyyən formatda çevirmək üçün istifadə olunur. | `SELECT STR_TO_DATE('07-02-2025', '%d-%m-%Y'); -- 2025-02-07` |
| `DATE_FORMAT(date, format)` | Tarixi müəyyən formatda qaytarır. | `SELECT DATE_FORMAT(NOW(), '%Y-%m-%d %H:%i:%s'); -- 2025-02-07 14:30:15` |

---


### 🔹 ** SQL Məntiqi Funksiyalar**  

| **Funksiya / Operator** | **Təsviri** | **Nümunə** |
|-------------------------|------------|------------|
| `AND` | Bütün şərtlər doğru olarsa, `TRUE` qaytarır. | `SELECT * FROM employees WHERE age > 25 AND salary > 5000;` |
| `OR` | Ən azı bir şərt doğru olarsa, `TRUE` qaytarır. | `SELECT * FROM employees WHERE age > 25 OR salary > 5000;` |
| `NOT` | Şərtin əksini qaytarır. | `SELECT * FROM employees WHERE NOT (age > 25);` |
| `XOR` | Şərtlərdən yalnız biri doğru olduqda `TRUE` qaytarır (MySQL). | `SELECT * FROM employees WHERE age > 25 XOR salary > 5000;` |
| `CASE` | Şərti ifadələr yaratmaq üçün istifadə olunur. | `SELECT name, salary, CASE WHEN salary > 5000 THEN 'High' ELSE 'Low' END AS salary_level FROM employees;` |
| `IF(condition, true_value, false_value)` | Şərt doğru olduqda `true_value`, əks halda `false_value` qaytarır (MySQL). | `SELECT IF(age > 30, 'Older', 'Younger') FROM employees;` |
| `IFNULL(expression, alt_value)` | Əgər ifadə `NULL` olarsa, alternativ dəyəri qaytarır. | `SELECT IFNULL(phone, 'No phone') FROM employees;` |
| `NULLIF(expression1, expression2)` | Əgər iki ifadə eyni olarsa, `NULL`, əks halda `expression1` qaytarır. | `SELECT NULLIF(10, 10); -- NULL` |
| `COALESCE(expression1, expression2, ...)` | İlk `NULL` olmayan dəyəri qaytarır. | `SELECT COALESCE(NULL, NULL, 'Default', 'Another'); -- 'Default'` |
| `NVL(expression, alt_value)` | Əgər ifadə `NULL` olarsa, alternativ dəyəri qaytarır (Oracle). | `SELECT NVL(phone, 'No phone') FROM employees;` |
| `NVL2(expression, value_if_not_null, value_if_null)` | İfadə `NULL` deyilsə, `value_if_not_null`, əks halda `value_if_null` qaytarır (Oracle). | `SELECT NVL2(phone, 'Has Phone', 'No Phone') FROM employees;` |
| `DECODE(expression, search1, result1, search2, result2, ..., default_value)` | `CASE` funksiyasına bənzəyir. Əgər `expression` `searchX` dəyərinə bərabərdirsə, müvafiq `resultX` qaytarır. Əgər uyğunluq tapılmazsa, `default_value` qaytarır (Oracle). | `SELECT DECODE(department, 'IT', 'Information Technology', 'HR', 'Human Resources', 'Other') FROM employees;` |
| `EXISTS(subquery)` | Alt sorğu nəticə qaytararsa, `TRUE`, əks halda `FALSE` qaytarır. | `SELECT * FROM employees WHERE EXISTS (SELECT 1 FROM departments WHERE department_id = employees.department_id);` |

---

### 🔹 ** SQL Agregat Funksiyalar**  

Agregat funksiyalar çoxlu sətirdən ibarət məlumatları bir nəticəyə gətirmək üçün istifadə olunur.

| **Funksiya** | **Təsviri** | **Nümunə** |
|--------------|------------|------------|
| `COUNT(column)` | Sətirlərin sayını qaytarır. | `SELECT COUNT(*) FROM employees;` |
| `SUM(column)` | Sütundakı rəqəmlərin cəmini qaytarır. | `SELECT SUM(salary) FROM employees;` |
| `AVG(column)` | Sütundakı rəqəmlərin orta dəyərini qaytarır. | `SELECT AVG(salary) FROM employees;` |
| `MAX(column)` | Sütundakı maksimum dəyəri qaytarır. | `SELECT MAX(salary) FROM employees;` |
| `MIN(column)` | Sütundakı minimum dəyəri qaytarır. | `SELECT MIN(salary) FROM employees;` |
| `GROUP_CONCAT(column)` | Bütün dəyərləri vergüllə ayıraraq birləşdirir (MySQL). | `SELECT GROUP_CONCAT(name) FROM employees;` |
| `STRING_AGG(column, separator)` | Bütün dəyərləri müəyyən ayırıcı ilə birləşdirir (PostgreSQL, SQL Server). | `SELECT STRING_AGG(name, ', ') FROM employees;` |
| `VARIANCE(column)` | Sütundakı dəyərlərin dispersiyasını qaytarır (Oracle, PostgreSQL). | `SELECT VARIANCE(salary) FROM employees;` |
| `STDDEV(column)` | Sütundakı dəyərlərin standart kənarlaşmasını qaytarır. | `SELECT STDDEV(salary) FROM employees;` |

🔹 **Qeyd:**  
- Agregat funksiyalar `GROUP BY` ilə birlikdə istifadə edilə bilər.  
- `NULL` dəyərlər standart olaraq nəzərə alınmır.  
- `HAVING` şərti ilə filtrasiya edilə bilər.

Əlavə sualın varsa, soruşa bilərsən! 😊

---


## 🔹 **Excel Funksiyaları**  


### **🔹Excel Mətni işləmək üçün funksiyalar (Text Functions)**

| **Funksiya** | **Təsviri** | **Nümunə** |
|--------------|-------------|------------|
| `CONCATENATE()` | Mətni birləşdirir. | `=CONCATENATE("Hello", " ", "World")` (Nəticə: "Hello World") |
| `LEFT()` | Mətndən başlanğıc nöqtəsindən müəyyən sayda simvolu qaytarır. | `=LEFT("Hello", 2)` (Nəticə: "He") |
| `RIGHT()` | Mətndən sona yaxın simvolları qaytarır. | `=RIGHT("Hello", 3)` (Nəticə: "llo") |
| `MID()` | Mətndən müəyyən başlanğıc mövqeyindən müəyyən sayda simvolu çıxarır. | `=MID("Hello", 2, 3)` (Nəticə: "ell") |
| `LEN()` | Mətnin uzunluğunu qaytarır. | `=LEN("Hello")` (Nəticə: 5) |
| `UPPER()` | Mətni böyük hərflə qaytarır. | `=UPPER("hello")` (Nəticə: "HELLO") |
| `LOWER()` | Mətni kiçik hərflə qaytarır. | `=LOWER("HELLO")` (Nəticə: "hello") |
| `PROPER()` | Hər kəlmənin ilk hərfini böyüdür. | `=PROPER("hello world")` (Nəticə: "Hello World") |
| `TRIM()` | Mətndəki əlavə boşluqları silir. | `=TRIM("  Hello World  ")` (Nəticə: "Hello World") |
| `REPLACE()` | Mətndəki bir hissəni dəyişdirir. | `=REPLACE("Hello", 2, 2, "a")` (Nəticə: "Hallo") |
| `SUBSTITUTE()` | Mətnin içində müəyyən simvolları dəyişdirir. | `=SUBSTITUTE("Hello World", "World", "Everyone")` (Nəticə: "Hello Everyone") |
| `TEXT()` | Sayıları müəyyən formatda mətniyə çevirir. | `=TEXT(1234.56, "#,##0.00")` (Nəticə: "1,234.56") |

---


### 🔹 **Excel Axtarış və İstinad Funksiyaları (Lookup & Reference Functions)**

| **Funksiya** | **Təsviri** | **Nümunə** |
|--------------|-------------|------------|
| `VLOOKUP()` | Cədvəlin sol tərəfindəki məlumatlardan müəyyən bir məlumatı axtarır və sağ tərəfdəki dəyəri qaytarır. | `=VLOOKUP(102, A2:B10, 2, FALSE)` |
| `HLOOKUP()` | Yatay olaraq cədvəlin bir hissəsində məlumat axtarır. | `=HLOOKUP(102, A1:F10, 3, FALSE)` |
| `INDEX()` | Cədvəldə müəyyən satır və sütun kəsişməsindən dəyəri qaytarır. | `=INDEX(A1:C10, 3, 2)` |
| `MATCH()` | Verilən dəyəri cədvəldə axtarır və həmin dəyərin mövqeyini qaytarır. | `=MATCH("Hello", A1:A10, 0)` |
| `OFFSET()` | Verilən hüceyrədən müəyyən məsafə ilə olan hüceyrəyə istinad edir. | `=OFFSET(A1, 2, 3)` |
| `INDIRECT()` | Mətnin göstərişi ilə verilən hüceyrə istinadını qaytarır. | `=INDIRECT("A1")` |
| `XLOOKUP()` | Verilən axtarış dəyərini cədvəlin istənilən yerində axtarır və uyğun dəyəri qaytarır (yeni versiyalar). | `=XLOOKUP(102, A2:A10, B2:B10)` |

---

**XLOOKUP()** Excel-in ən yeni funksiyalarından biridir və `VLOOKUP`-dan fərqli olaraq, daha çox çevikdir. `XLOOKUP` həm yatay, həm də şaquli axtarışları asanlaşdırır, habelə axtarış qiyməti tapılmadıqda alternativ bir dəyər qaytarmaq imkanı verir.

### **XLOOKUP Nümunəsi:**
```excel
=XLOOKUP(102, A2:A10, B2:B10, "Not Found")
```
Bu funksiya 102 qiymətini `A2:A10` aralığında axtarır və taparsa, uyğun olan `B2:B10` aralığındakı dəyəri qaytarır. Əgər tapmazsa, "Not Found" mətnini qaytarır.

Əlavə sualınız varsa, soruşa bilərsiniz! 😊

---

### **🔹Excel Hesablama və statistik funksiyalar (Mathematical & Statistical Functions)**

| **Funksiya** | **Təsviri** | **Nümunə** |
|--------------|-------------|------------|
| `SUM()` | Verilən hüceyrələrdəki rəqəmlərin cəmini qaytarır. | `=SUM(A1:A5)` |
| `AVERAGE()` | Verilən hüceyrələrdəki rəqəmlərin ortalamasını qaytarır. | `=AVERAGE(A1:A5)` |
| `COUNT()` | Verilən hüceyrələrdəki ədədlərin sayını qaytarır. | `=COUNT(A1:A5)` |
| `MIN()` | Verilən hüceyrələrdəki ən kiçik rəqəmi qaytarır. | `=MIN(A1:A5)` |
| `MAX()` | Verilən hüceyrələrdəki ən böyük rəqəmi qaytarır. | `=MAX(A1:A5)` |
| `ROUND()` | Rəqəmi müəyyən sayda ondalıklı ilə yuvarlaqlaşdırır. | `=ROUND(3.14159, 2)` |
| `CEILING()` | Rəqəmi müəyyən bir çoxaldaqi ilə yuxarıya yuvarlaqlaşdırır. | `=CEILING(7.25, 0.5)` |
| `FLOOR()` | Rəqəmi müəyyən bir çoxaldaqi ilə aşağıya yuvarlaqlaşdırır. | `=FLOOR(7.25, 0.5)` |
| `MOD()` | İki rəqəmin qalıq hissəsini qaytarır. | `=MOD(10, 3)` (Nəticə: 1) |

---

### **🔹Excel Şərt funksiyaları (Logical Functions)**

| **Funksiya** | **Təsviri** | **Nümunə** |
|--------------|-------------|------------|
| `IF()` | Şərtə əsasən dəyər qaytarır. | `=IF(A1 > 10, "Greater", "Smaller")` |
| `AND()` | Bir neçə şərtin doğru olub-olmamasını yoxlayır. | `=AND(A1 > 5, B1 < 10)` |
| `OR()` | Bir neçə şərtdən ən az birinin doğru olub-olmamasını yoxlayır. | `=OR(A1 > 5, B1 < 10)` |
| `NOT()` | Şərtin əksini qaytarır. | `=NOT(A1 > 10)` |
| `IFERROR()` | Əgər bir formul səhv qaytararsa, alternativ dəyər göstərir. | `=IFERROR(A1/B1, "Error")` |

---

### **🔹 Excel Tarix və Zaman funksiyaları (Date & Time Functions)**

| **Funksiya** | **Təsviri** | **Nümunə** |
|--------------|-------------|------------|
| `TODAY()` | Bugünün tarixini qaytarır. | `=TODAY()` |
| `NOW()` | Hazırkı tarix və vaxtı qaytarır. | `=NOW()` |
| `DATE()` | Verilən il, ay və gündən tarix yaradır. | `=DATE(2022, 12, 31)` |
| `DATEDIF()` | İki tarix arasındakı fərqi hesablamaq üçün istifadə olunur. | `=DATEDIF(A1, B1, "Y")` |
| `YEAR()` | Verilən tarixdən ili çıxarır. | `=YEAR(A1)` |
| `MONTH()` | Verilən tarixdən ayı çıxarır. | `=MONTH(A1)` |
| `DAY()` | Verilən tarixdən günü çıxarır. | `=DAY(A1)` |
| `TIME()` | Verilən saat, dəqiqə və saniyədən vaxt yaradır. | `=TIME(14, 30, 0)` |

---