# Data Cleaning In Python

### Common Issues With Data
+ Reading the file
+ Inconsistent Column Names
+ Missing Data
+ Different Data Types
+ Duplicate rows
+ etc

In [ ]:
# EDA packages
import pandas as pd
import numpy as np

## Loading or Reading the File
+ Encoding Error
+ Inconsistent rows

In [ ]:
# Issue 1
df = pd.read_csv("unclean_data.csv")

In [ ]:
df.head()

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
0,Avatar,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN

## Inconsistent Column Names
+ Change Cases
+ Rename them

### Change the case to Upper

In [ ]:
df.columns # bringing column names

Index(['movie_title', 'num_critic_for_reviews', 'duration',
       'DIRECTOR_facebook_likes', 'actor_3_facebook_likes',
       'ACTOR_1_facebook_likes', 'gross', 'num_voted_users',
       'Cast_Total_facebook_likes', 'facenumber_in_poster',
       'num_user_for_reviews', 'budget', 'title_year',
       'ACTOR_2_facebook_likes', 'imdb_score', 'title_year.1'],
      dtype='object')

In [ ]:
df.columns.str.upper() # Uppering selected strings

Index(['MOVIE_TITLE', 'NUM_CRITIC_FOR_REVIEWS', 'DURATION',
       'DIRECTOR_FACEBOOK_LIKES', 'ACTOR_3_FACEBOOK_LIKES',
       'ACTOR_1_FACEBOOK_LIKES', 'GROSS', 'NUM_VOTED_USERS',
       'CAST_TOTAL_FACEBOOK_LIKES', 'FACENUMBER_IN_POSTER',
       'NUM_USER_FOR_REVIEWS', 'BUDGET', 'TITLE_YEAR',
       'ACTOR_2_FACEBOOK_LIKES', 'IMDB_SCORE', 'TITLE_YEAR.1'],
      dtype='object')

In [ ]:
df.columns

Index(['movie_title', 'num_critic_for_reviews', 'duration',
       'DIRECTOR_facebook_likes', 'actor_3_facebook_likes',
       'ACTOR_1_facebook_likes', 'gross', 'num_voted_users',
       'Cast_Total_facebook_likes', 'facenumber_in_poster',
       'num_user_for_reviews', 'budget', 'title_year',
       'ACTOR_2_facebook_likes', 'imdb_score', 'title_year.1'],
      dtype='object')

In [ ]:
df.columns = df.columns.str.upper()

In [ ]:
df.columns

Index(['MOVIE_TITLE', 'NUM_CRITIC_FOR_REVIEWS', 'DURATION',
       'DIRECTOR_FACEBOOK_LIKES', 'ACTOR_3_FACEBOOK_LIKES',
       'ACTOR_1_FACEBOOK_LIKES', 'GROSS', 'NUM_VOTED_USERS',
       'CAST_TOTAL_FACEBOOK_LIKES', 'FACENUMBER_IN_POSTER',
       'NUM_USER_FOR_REVIEWS', 'BUDGET', 'TITLE_YEAR',
       'ACTOR_2_FACEBOOK_LIKES', 'IMDB_SCORE', 'TITLE_YEAR.1'],
      dtype='object')

### Renaming Columns

In [ ]:
df.rename(columns = {'DURATION':'TIME'})

,MOVIE_TITLE,NUM_CRITIC_FOR_REVIEWS,TIME,DIRECTOR_FACEBOOK_LIKES,ACTOR_3_FACEBOOK_LIKES,ACTOR_1_FACEBOOK_LIKES,GROSS,NUM_VOTED_USERS,CAST_TOTAL_FACEBOOK_LIKES,FACENUMBER_IN_POSTER,NUM_USER_FOR_REVIEWS,BUDGET,TITLE_YEAR,ACTOR_2_FACEBOOK_LIKES,IMDB_SCORE,TITLE_YEAR.1
0,Avatar,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN
5,Spider-Man 3,392,156.0,23,4000,24000,336530303,383056.0,46055.0,NaN,1902,258000000,2007,11000.0,6.2,2007.0
6,Tangled,324,NaN,15,284,799,200807262,294810.0,NaN,1.0,387,260000000,2010,553.0,7.8,NaN
7,Avengers: Age of Ultron?ÿ,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,NaN
8,Avengers: Age of Ultron,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,2015.0
9,Harry Potter and the Half-Blood Prince,375,153.0,282,10000,25000,301956980,321795.0,58753.0,3.0,973,250000000,2009,11000.0,7.5,NaN
10,Batman v Superman: Dawn of Justice,673,183.0,NaN,2000,15000,330249062,NaN,24450.0,NaN,3018,250000000,2016,NaN,6.9,2016.0
11,Superman Returns,434,169.0,NaN,903,18000,200069408,240396.0,NaN,2.0,2367,209000000,2006,10000.0,6.1,NaN
12,Quantum of Solace,403,106.0,395,393,451,168368427,330784.0,2023.0,1.0,1243,200000000,2008,412.0,6.7,2008.0
13,Pirates of the Caribbean: Dead Man's Chest,313,151.0,563,1000,40000,423032628,522040.0,48486.0,2.0,1832,225000000,2006,5000.0,7.3,2008.0

## Missing Data
+ Add a default value for missing data or use mean to fill it
+ Delete the row/column with missing data
+ Interpolate the rows
+ Replace

#### To check for missing data
#### False means no missing data
+ df.isnull().sum() int
+ df.isnull().any() bool

In [ ]:
df.isnull()

,MOVIE_TITLE,NUM_CRITIC_FOR_REVIEWS,DURATION,DIRECTOR_FACEBOOK_LIKES,ACTOR_3_FACEBOOK_LIKES,ACTOR_1_FACEBOOK_LIKES,GROSS,NUM_VOTED_USERS,CAST_TOTAL_FACEBOOK_LIKES,FACENUMBER_IN_POSTER,NUM_USER_FOR_REVIEWS,BUDGET,TITLE_YEAR,ACTOR_2_FACEBOOK_LIKES,IMDB_SCORE,TITLE_YEAR.1
0,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
5,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
6,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,True
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
10,False,False,False,True,False,False,False,True,False,True,False,False,False,True,False,False
11,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().any()

MOVIE_TITLE                  False
NUM_CRITIC_FOR_REVIEWS       False
DURATION                      True
DIRECTOR_FACEBOOK_LIKES       True
ACTOR_3_FACEBOOK_LIKES       False
ACTOR_1_FACEBOOK_LIKES       False
GROSS                        False
NUM_VOTED_USERS               True
CAST_TOTAL_FACEBOOK_LIKES     True
FACENUMBER_IN_POSTER          True
NUM_USER_FOR_REVIEWS         False
BUDGET                       False
TITLE_YEAR                   False
ACTOR_2_FACEBOOK_LIKES        True
IMDB_SCORE                   False
TITLE_YEAR.1                  True
dtype: bool

In [ ]:
# Columns with NAN using True/False
# False means it doesn't have a NAN
df.isnull().any()

MOVIE_TITLE                  False
NUM_CRITIC_FOR_REVIEWS       False
DURATION                      True
DIRECTOR_FACEBOOK_LIKES       True
ACTOR_3_FACEBOOK_LIKES       False
ACTOR_1_FACEBOOK_LIKES       False
GROSS                        False
NUM_VOTED_USERS               True
CAST_TOTAL_FACEBOOK_LIKES     True
FACENUMBER_IN_POSTER          True
NUM_USER_FOR_REVIEWS         False
BUDGET                       False
TITLE_YEAR                   False
ACTOR_2_FACEBOOK_LIKES        True
IMDB_SCORE                   False
TITLE_YEAR.1                  True
dtype: bool

In [ ]:
# For entire DataFrame
df.isnull().any().any()

True

In [ ]:
# Columns with NAN using Integer
df.isnull().sum()

MOVIE_TITLE                  0
NUM_CRITIC_FOR_REVIEWS       0
DURATION                     3
DIRECTOR_FACEBOOK_LIKES      2
ACTOR_3_FACEBOOK_LIKES       0
ACTOR_1_FACEBOOK_LIKES       0
GROSS                        0
NUM_VOTED_USERS              1
CAST_TOTAL_FACEBOOK_LIKES    2
FACENUMBER_IN_POSTER         5
NUM_USER_FOR_REVIEWS         0
BUDGET                       0
TITLE_YEAR                   0
ACTOR_2_FACEBOOK_LIKES       1
IMDB_SCORE                   0
TITLE_YEAR.1                 7
dtype: int64

In [ ]:
# Total Number of Missing NA
df.isnull().sum().sum()

21

# Working with missing variables

Numerical variables:
    * Min/max imputation
    * mean/median imputation
    * Arbitary value imputation
    * end of tail imputation
    
Catigorical variables:
    * Mode imputation
    * "missing" labeling
    
Both types:
    * Compleate Case Analaysis (CCA)
    * "missing" indicator
    * Random sample imputation

# Min/Max Imputation

when to use:
    * if data has to it a given range
    * if from data collection you know data closes to min or max values

In [ ]:
df['DURATION'].max() # for min type min instead of max

183.0

In [ ]:
df_with_max = df.DURATION.fillna(df['DURATION'].max())

# Mean / Median imputation

what to consider :
    * if normal distributed then mean = median
    * if skewed use median
    * if percentage of missing is less than 5%

In [ ]:
# Fill it with the mean
df['DURATION'].mean()# for median type median instead of mean

150.72727272727272

In [ ]:
df_with_mean = df.DURATION.fillna(df['DURATION'].mean())

In [ ]:
df_with_mean

0     178.000000
1     150.727273
2     148.000000
3     150.727273
4     132.000000
5     156.000000
6     150.727273
7     141.000000
8     141.000000
9     153.000000
10    183.000000
11    169.000000
12    106.000000
13    151.000000
Name: DURATION, dtype: float64

###  Arbitary imputation / Adding A Default Value or Filling the Missing Data

when and why to use:
    * Missing is not random
    * for flaging the missing places with solving labeling problem

In [ ]:
df.head()

,MOVIE_TITLE,NUM_CRITIC_FOR_REVIEWS,DURATION,DIRECTOR_FACEBOOK_LIKES,ACTOR_3_FACEBOOK_LIKES,ACTOR_1_FACEBOOK_LIKES,GROSS,NUM_VOTED_USERS,CAST_TOTAL_FACEBOOK_LIKES,FACENUMBER_IN_POSTER,NUM_USER_FOR_REVIEWS,BUDGET,TITLE_YEAR,ACTOR_2_FACEBOOK_LIKES,IMDB_SCORE,TITLE_YEAR.1
0,Avatar,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN

In [ ]:
df_with_arb = df.fillna("9999999")

In [ ]:
df_with_arb.head()

,MOVIE_TITLE,NUM_CRITIC_FOR_REVIEWS,DURATION,DIRECTOR_FACEBOOK_LIKES,ACTOR_3_FACEBOOK_LIKES,ACTOR_1_FACEBOOK_LIKES,GROSS,NUM_VOTED_USERS,CAST_TOTAL_FACEBOOK_LIKES,FACENUMBER_IN_POSTER,NUM_USER_FOR_REVIEWS,BUDGET,TITLE_YEAR,ACTOR_2_FACEBOOK_LIKES,IMDB_SCORE,TITLE_YEAR.1
0,Avatar,723,178,10,855,1000,760505847,886204,4834,9999999,3054,237000000,2009,936,7.9,2009
1,Pirates of the Caribbean: At World's End,302,9999999,563,1000,40000,309404152,471220,48350,9999999,1238,300000000,2007,5000,7.1,9999999
2,Spectre,602,148,20,161,11000,200074175,275868,11700,1,994,245000000,2015,393,6.8,2015
3,The Dark Knight Rises,813,9999999,22000,23000,27000,448130642,1.14434e+06,106759,9999999,2701,250000000,2012,23000,8.5,9999999
4,John Carter,462,132,"""475""",530,640,73058679,212204,1873,1,738,263700000,2012,632,6.6,9999999

# Imputing categorical variables

# Mode imputation / frequency

when to use:
    * missing is random
    * less than 5% missing
    * The missing observations most likely look like the majority of the observations

In [ ]:
df['TITLE_YEAR'].mode()

0    2015
dtype: int64

In [ ]:
df_with_mode = df.TITLE_YEAR.fillna(df['TITLE_YEAR'].mode())

In [ ]:
df_with_mode

0     2009
1     2007
2     2015
3     2012
4     2012
5     2007
6     2010
7     2015
8     2015
9     2009
10    2016
11    2006
12    2008
13    2006
Name: TITLE_YEAR, dtype: int64

# Missing Category Imputation

In [ ]:
df_with_missing = df.fillna("Missing")

In [ ]:
df_with_missing

,MOVIE_TITLE,NUM_CRITIC_FOR_REVIEWS,DURATION,DIRECTOR_FACEBOOK_LIKES,ACTOR_3_FACEBOOK_LIKES,ACTOR_1_FACEBOOK_LIKES,GROSS,NUM_VOTED_USERS,CAST_TOTAL_FACEBOOK_LIKES,FACENUMBER_IN_POSTER,NUM_USER_FOR_REVIEWS,BUDGET,TITLE_YEAR,ACTOR_2_FACEBOOK_LIKES,IMDB_SCORE,TITLE_YEAR.1
0,Avatar,723,178,10,855,1000,760505847,886204,4834,Missing,3054,237000000,2009,936,7.9,2009
1,Pirates of the Caribbean: At World's End,302,Missing,563,1000,40000,309404152,471220,48350,Missing,1238,300000000,2007,5000,7.1,Missing
2,Spectre,602,148,20,161,11000,200074175,275868,11700,1,994,245000000,2015,393,6.8,2015
3,The Dark Knight Rises,813,Missing,22000,23000,27000,448130642,1.14434e+06,106759,Missing,2701,250000000,2012,23000,8.5,Missing
4,John Carter,462,132,"""475""",530,640,73058679,212204,1873,1,738,263700000,2012,632,6.6,Missing
5,Spider-Man 3,392,156,23,4000,24000,336530303,383056,46055,Missing,1902,258000000,2007,11000,6.2,2007
6,Tangled,324,Missing,15,284,799,200807262,294810,Missing,1,387,260000000,2010,553,7.8,Missing
7,Avengers: Age of Ultron?ÿ,635,141,10,19000,26000,458991599,462669,92000,4,1117,250000000,2015,21000,7.5,Missing
8,Avengers: Age of Ultron,635,141,10,19000,26000,458991599,462669,92000,4,1117,250000000,2015,21000,7.5,2015
9,Harry Potter and the Half-Blood Prince,375,153,282,10000,25000,301956980,321795,58753,3,973,250000000,2009,11000,7.5,Missing
10,Batman v Superman: Dawn of Justice,673,183,Missing,2000,15000,330249062,Missing,24450,Missing,3018,250000000,2016,Missing,6.9,2016
11,Superman Returns,434,169,Missing,903,18000,200069408,240396,Missing,2,2367,209000000,2006,10000,6.1,Missing
12,Quantum of Solace,403,106,395,393,451,168368427,330784,2023,1,1243,200000000,2008,412,6.7,2008
13,Pirates of the Caribbean: Dead Man's Chest,313,151,563,1000,40000,423032628,522040,48486,2,1832,225000000,2006,5000,7.3,2008

# For both types of variables missing imputation

### Droping NA

In [ ]:
## Droping NA
df.head()

,MOVIE_TITLE,NUM_CRITIC_FOR_REVIEWS,DURATION,DIRECTOR_FACEBOOK_LIKES,ACTOR_3_FACEBOOK_LIKES,ACTOR_1_FACEBOOK_LIKES,GROSS,NUM_VOTED_USERS,CAST_TOTAL_FACEBOOK_LIKES,FACENUMBER_IN_POSTER,NUM_USER_FOR_REVIEWS,BUDGET,TITLE_YEAR,ACTOR_2_FACEBOOK_LIKES,IMDB_SCORE,TITLE_YEAR.1
0,Avatar,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN

In [ ]:
df.isnull().sum().sum()

21

In [ ]:
df.shape

(14, 16)

In [ ]:
df_drop = df.dropna()

In [ ]:
df_drop.shape

(4, 16)

In [ ]:
df_drop.head()

,MOVIE_TITLE,NUM_CRITIC_FOR_REVIEWS,DURATION,DIRECTOR_FACEBOOK_LIKES,ACTOR_3_FACEBOOK_LIKES,ACTOR_1_FACEBOOK_LIKES,GROSS,NUM_VOTED_USERS,CAST_TOTAL_FACEBOOK_LIKES,FACENUMBER_IN_POSTER,NUM_USER_FOR_REVIEWS,BUDGET,TITLE_YEAR,ACTOR_2_FACEBOOK_LIKES,IMDB_SCORE,TITLE_YEAR.1
2,Spectre,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
8,Avengers: Age of Ultron,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,2015.0
12,Quantum of Solace,403,106.0,395,393,451,168368427,330784.0,2023.0,1.0,1243,200000000,2008,412.0,6.7,2008.0
13,Pirates of the Caribbean: Dead Man's Chest,313,151.0,563,1000,40000,423032628,522040.0,48486.0,2.0,1832,225000000,2006,5000.0,7.3,2008.0

In [ ]:
?df.dropna

In [ ]:
df_drop_with_condition = df.dropna(thresh=2)

In [ ]:
df_drop_with_condition.shape

(14, 16)

In [ ]:
df.shape

(14, 16)

In [ ]:
df_drop_column = df.dropna(axis=1)

In [ ]:
df_drop_column.shape

(14, 9)

# Missing Indicator

In [ ]:
from sklearn.impute import MissingIndicator

In [ ]:
indicator = MissingIndicator(error_on_new=True, features='missing-only')

In [ ]:
df_mi = df

In [ ]:
indicator.fit(df_mi)

MissingIndicator(error_on_new=True, features='missing-only', missing_values=nan,
                 sparse='auto')

In [ ]:
# print the columns of missing data.

print(df_mi.columns[indicator.features_])

Index(['DURATION', 'DIRECTOR_FACEBOOK_LIKES', 'NUM_VOTED_USERS',
       'CAST_TOTAL_FACEBOOK_LIKES', 'FACENUMBER_IN_POSTER',
       'ACTOR_2_FACEBOOK_LIKES', 'TITLE_YEAR.1'],
      dtype='object')

In [ ]:
# get the columns of missing indicators.
temporary = indicator.transform(df_mi)

In [ ]:
# create a column name for each of the new Missing indicators
indicator_columns = [column +'_NA_IND' for column in df_mi.columns[indicator.features_]]
indicator_df = pd.DataFrame(temporary, columns = indicator_columns)

In [ ]:
# create the final train data.
df_with_mi = pd.concat([df_mi.reset_index(), indicator_df], axis=1)

In [ ]:
df_with_mi

,index,MOVIE_TITLE,NUM_CRITIC_FOR_REVIEWS,DURATION,DIRECTOR_FACEBOOK_LIKES,ACTOR_3_FACEBOOK_LIKES,ACTOR_1_FACEBOOK_LIKES,GROSS,NUM_VOTED_USERS,CAST_TOTAL_FACEBOOK_LIKES,...,ACTOR_2_FACEBOOK_LIKES,IMDB_SCORE,TITLE_YEAR.1,DURATION_NA_IND,DIRECTOR_FACEBOOK_LIKES_NA_IND,NUM_VOTED_USERS_NA_IND,CAST_TOTAL_FACEBOOK_LIKES_NA_IND,FACENUMBER_IN_POSTER_NA_IND,ACTOR_2_FACEBOOK_LIKES_NA_IND,TITLE_YEAR.1_NA_IND
0,0,Avatar,723,178.0,10,855,1000,760505847,886204.0,4834.0,...,936.0,7.9,2009.0,False,False,False,False,True,False,False
1,1,Pirates of the Caribbean: At World's End,302,NaN,563,1000,40000,309404152,471220.0,48350.0,...,5000.0,7.1,NaN,True,False,False,False,True,False,True
2,2,Spectre,602,148.0,20,161,11000,200074175,275868.0,11700.0,...,393.0,6.8,2015.0,False,False,False,False,False,False,False
3,3,The Dark Knight Rises,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,...,23000.0,8.5,NaN,True,False,False,False,True,False,True
4,4,John Carter,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,...,632.0,6.6,NaN,False,False,False,False,False,False,True
5,5,Spider-Man 3,392,156.0,23,4000,24000,336530303,383056.0,46055.0,...,11000.0,6.2,2007.0,False,False,False,False,True,False,False
6,6,Tangled,324,NaN,15,284,799,200807262,294810.0,NaN,...,553.0,7.8,NaN,True,False,False,True,False,False,True
7,7,Avengers: Age of Ultron?ÿ,635,141.0,10,19000,26000,458991599,462669.0,92000.0,...,21000.0,7.5,NaN,False,False,False,False,False,False,True
8,8,Avengers: Age of Ultron,635,141.0,10,19000,26000,458991599,462669.0,92000.0,...,21000.0,7.5,2015.0,False,False,False,False,False,False,False
9,9,Harry Potter and the Half-Blood Prince,375,153.0,282,10000,25000,301956980,321795.0,58753.0,...,11000.0,7.5,NaN,False,False,False,False,False,False,True
10,10,Batman v Superman: Dawn of Justice,673,183.0,NaN,2000,15000,330249062,NaN,24450.0,...,NaN,6.9,2016.0,False,True,True,False,True,True,False
11,11,Superman Returns,434,169.0,NaN,903,18000,200069408,240396.0,NaN,...,10000.0,6.1,NaN,False,True,False,True,False,False,True
12,12,Quantum of Solace,403,106.0,395,393,451,168368427,330784.0,2023.0,...,412.0,6.7,2008.0,False,False,False,False,False,False,False
13,13,Pirates of the Caribbean: Dead Man's Chest,313,151.0,563,1000,40000,423032628,522040.0,48486.0,...,5000.0,7.3,2008.0,False,False,False,False,False,False,False

In [ ]:
 a = pd.Series(["500$", "450$", '570$'])

In [ ]:
a

0    500$
1    450$
2    570$
dtype: object

In [ ]:
a.astype("int64")

ValueError: invalid literal for int() with base 10: '500$'

In [ ]:
a = a.str.replace('$', '', regex=True)

In [ ]:
a

0    500
1    450
2    570
dtype: object

In [ ]:
a.astype("int64")

0    500
1    450
2    570
dtype: int64